name: Tun Tests using Cy Action

on: [push]

jobs:
  cypress-run-cy-action:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          record: true
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.DASHBOARD_KEY }}