name: Run Cypress Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  cypress-run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo code
      uses: actions/checkout@v2
    - name: CI Setup
      run: |
          npm ci
          npm run cy:verify
          npm run cy:info
    - name: Execute Cypress tests
      run: npm run cy:run -- --record --key ${{ secrets.DASHBOARD_KEY }}
